controllers/BookRoomControl.py
from flask import Blueprint, session, redirect, url_for, request, render_template
from views.dashboardView import Dashboard
from views.adminAccountView import AdminAccountPage
from views.homeView import Home
from views.searchroomview import SearchRoomView
from core.user import User
from models.RoomModel import RoomModel

bookroom_bp = Blueprint('bookroom', __name__)

@bookroom_bp.route('/bookroom/<int:room_id>/<string:action>', methods=['GET','POST'])
def bookroom(room_id, action):
    
    if action == 'book':
        user = User(session['user'])
        u = user.getuserID()
        
        room = RoomModel().get_room_by_id(room_id)
        
        form_data = {
            'student_id': user.getuserID() if user.getuserID() != None else '',
            'first_name': user.getfName() if user.getuserID() != None else '',
            'last_name': user.getlName() if user.getuserID() != None else '',
            'email': user.getemail() if user.getuserID() != None else '',  
            'action': action,
            'room_id':room.get_room_id()
        }
        
    
    return render_template('application.html', room=room, errors={}, form_data=form_data, user=user)

controllers/DashboardControl.py
from flask import Blueprint, session, redirect, url_for, request
from views.dashboardView import Dashboard
from views.adminAccountView import AdminAccountPage
from views.homeView import Home
from views.searchroomview import SearchRoomView
from core.user import User

dashboard_bp = Blueprint('dashboard', __name__)

@dashboard_bp.route('/dashboard', methods=['GET'])
def dashboard():
    
    return Dashboard(User(session['user'])).index()



@dashboard_bp.route('/room_search', methods=['GET'])
def room_search():
    return SearchRoomView(User(session['user'])).index()


@dashboard_bp.route('/admin_account_page/<int:userID>', methods=['GET'])
def admin_account_page(userID):
    user = session['user']
    # Ensuring that its the same user that was verified and login (calling this page)
    if session['user']['userID'] == userID:
        
        return AdminAccountPage(session['user']).index()
    
    return Home().index()

@dashboard_bp.route("/logout", methods=["POST", "GET"])
def logout():
    session.clear()
    return redirect(url_for('login.login'))

controllers/LoginControl.py
from flask import Blueprint, request
from views.loginView import Login


login_bp = Blueprint('login', __name__)

@login_bp.route('/login', methods=['GET', 'POST'])
def login():
    loginObj = Login()
    
    if request.method == "POST":
        return loginObj.login()
    
    return loginObj.index()

controllers/SearchRoomControl.py
from flask import Blueprint, session, redirect, url_for, request, render_template
from views.dashboardView import Dashboard
from views.adminAccountView import AdminAccountPage
from views.homeView import Home
from views.searchroomview import SearchRoomView
from core.user import User
from models.RoomModel import RoomModel

searchroom_bp = Blueprint('searchroom', __name__)

@searchroom_bp.route('/search_room', methods=['POST'])
def search_room():
    u = session['user']
    user = User(session['user'])
    
    if user.getuserType() not in ['Student', 'Admin']:
        return redirect(url_for('dashboard.dashboard'))
    
    rooms = []
    if request.method == 'POST':
        room_type = request.form.get('room_type')
        dormitory = request.form.get('dormitory')  
        level = request.form.get('level')  
        availability = request.form.get('availability')
        
        # Query the database based on the search criteria
        # Create filters dictionary
        filters = {
            'room_type': room_type,
            'building': dormitory,
            'floor_number': level,
            'available_rooms': availability  # Or other availability logic
        }
        
        # Get filtered rooms
        rooms = RoomModel().getRooms(filters)
        
    
    return render_template('searchroom.html', rooms=rooms, user=User(session['user']))

views/dashboardView.py
from flask import render_template
from core.user import User
from models.database import Database

class Dashboard:
    __user = None
    
    def __init__(self, user: User):
        self.__user = user
    
    def index(self):
        dashboardData = []
        if self.__user.getuserType() == "Student":
            dashboardData = self.__user.getAllApplications()
            
        if self.__user.getuserType() == "Admin":
            dashboardData = self.__user.getAllApplications()
            
        if self.__user.getuserType() == "IT":
            selectQuery = 'SELECT * from users where usertype = %s'
            selectValue = ('Admin',)
            
            
            adminUsers = Database().exec(selectQuery, selectValue, fetch=True)
            
            for user in adminUsers:
                dashboardData.append(User(user))
        
        return render_template('dashboard.html', user=self.__user, values=dashboardData)

views/loginView.py
from flask import render_template, request, session
from models.UsersModel import UsersModel
from views.dashboardView import Dashboard
from models.database import Database
from core.user import User

# MVC
# Model View Control
# Model = database
# View = html files
# Control = route
class Login:

    
    def index(self):
        return render_template('login.html')
    
    
    def login(self):
 
        # session.pop('_flashes', None)
        
        self.userID = int(request.form.get('userID'))
        self.password = request.form.get('password')
    
        
        self.user = UsersModel(self.userID, self.password).getUser()

        if self.user.getuserID() != None:
            
            session['user'] = self.user.to_dict()
                  
            return Dashboard(self.user).index()
            
        
        return self.index()
    
    
        #     if self.user:
            
        #     session['user'] = self.user.to_dict()
            
        #     selectQuery = 'SELECT * from users where usertype = %s'
        #     selectValue = ('Admin',)
            
            
        #     adminUsers = Database().exec(selectQuery, selectValue, fetch=True)
        #     users = []
        #     for user in adminUsers:
        #        users.append(User(user))
            
        #     return Dashboard(self.user).index(values=users)
            
        
        # return self.index()
        

views/searchroomview.py
from flask import render_template
from core.user import User

class SearchRoomView:
    __user = None
    
    def __init__(self, user: User):
        self.__user = user
    
    def index(self):
        return render_template('searchroom.html', user=self.__user)

templates/admin_account_page.html
{% extends "sidebar.html" %}

{% block content %}
<!-- Main Content -->
<div class="content p-4 mx-auto" style="width: 50%; max-width: 1200px;">
    <h1 class="text-center mb-4">Create Admin Account</h1>
    <form method="POST" action="/create_admin_account">

        <!-- Admin ID -->
        <div class="mb-3">
            <label for="adminID" class="form-label">Staff ID</label>
            <input type="text" class="form-control" id="adminID" name="adminID" value="{{ form_data.adminID if form_data else '' }}" placeholder="Enter your Staff ID" >
            
            {% if errors.student_id %}
                <div class="text-danger">{{ errors.adminID }}</div>
            {% endif %}
        </div>

        <!-- First Name -->
        <div class="mb-3">
            <label for="firstName" class="form-label">First Name</label>
            <input type="text" class="form-control" id="firstName" name="first_name" value="{{ form_data.first_name if form_data else '' }}" placeholder="Enter Staff First Name" >
            
            {% if errors.first_name %}
                <div class="text-danger">{{ errors.first_name }}</div>
            {% endif %}
        </div>

        <!-- Last Name -->
        <div class="mb-3">
            <label for="lastName" class="form-label">Last Name</label>
            <input type="text" class="form-control" id="lastName" name="last_name" value="{{ form_data.last_name if form_data else '' }}" placeholder="Enter staff Last Name" >
        
            {% if errors.last_name %}
                <div class="text-danger">{{ errors.last_name }}</div>
            {% endif %}
        </div>

        <!-- Middle Name -->
        <div class="mb-3">
            <label for="middleName" class="form-label">Middle Name</label>
            <input type="text" class="form-control" id="middleName" name="middle_name" value="{{ form_data.middle_name if form_data else '' }}" placeholder="Enter Staff Middle Name">
        </div>

        <!-- Email -->
        <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input type="email" class="form-control" id="email" name="email" value="{{ form_data.email if form_data else '' }}" placeholder="Enter Staff Email" >
        
            {% if errors.email %}
                <div class="text-danger">{{ errors.email }}</div>
            {% endif %}
        </div>

        <!-- Telephone -->
        <div class="mb-3">
            <label for="telephone" class="form-label">Telephone</label>
            <input type="tel" class="form-control" id="telephone" name="telephone" value="{{ form_data.telephone if form_data else '' }}" placeholder="Enter Staff Telephone Number" >
        
            {% if errors.telephone %}
                <div class="text-danger">{{ errors.telephone }}</div>
            {% endif %}
        </div>

        <!-- Gender -->
        <div class="mb-3">
            <label for="gender" class="form-label">Gender</label>
            <select id="gender" name="gender" class="form-control" >
                <option value="" disabled {% if not form_data.gender %}selected{% endif %}>Select Gender</option>
                <option value="male" {% if form_data.gender == 'male' %}selected{% endif %}>Male</option>
                <option value="female" {% if form_data.gender == 'female' %}selected{% endif %}>Female</option>
                <option value="other" {% if form_data.gender == 'other' %}selected{% endif %}>Other</option>
            </select>

            {% if errors.gender %}
                <div class="text-danger">{{ errors.gender }}</div>
            {% endif %}
        </div>

        <!-- Buttons -->
        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-success">Save Admin Account</button>
        </div>
    </form>
</div>


{% endblock content %}

templates/application.html
{% extends "sidebar.html" %}

{% block content %}

<div class="content p-4 mx-auto" style="width: 50%; max-width: 1200px;">
    <h1 class="text-center mb-4">Book Room</h1>
    {% if room %}
        <div class="container mt-5">
            <div class="card mb-3">
                <div class="row g-0">
                    <!-- Image -->
                    <div class="col-md-4">
                        <img src="{{ url_for("static", filename=room.get_image_url()) }}" class="img-fluid rounded-start" alt="Room Image">
                    </div>
                    <!-- Text -->
                    <div class="col-md-8 d-flex align-items-center">
                        <div class="card-body">
                            <h5 class="card-title">{{ room.get_room_type().title() ~ " Rooms for Building " ~ room.get_building() ~ " - Floor Level " ~ room.get_floor_number() }}</h5>
                            <p class="card-text">{{ room.get_description() }}</p>
                            <!-- <p class="card-text"><small class="text-muted">Available: {{ room.available_rooms }}</small></p> -->
                            
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">Available: {{ room.get_available_rooms() }}</small>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    <form method="POST" 
      action="{% if form_data.action == 'book' %}
                {{ url_for('application.submitApplication', room_id=room.get_room_id(), action='book') }}
              {% else %}
                /edit_application/{{ form_data.room_id }}
              {% endif %}">

        {% if room %}
            <input type="hidden" name="room_id" value="{{ room.get_room_id() }}">
        {% endif %}
        {% if errors.room %}
            <div class="text-danger">{{ errors.room }}</div>
        {% endif %}

        <!-- Student ID -->
        <div class="mb-3">
            <label for="studentId" class="form-label">Student ID</label>
            <input type="text" class="form-control" id="studentId" name="student_id" value="{{ form_data.student_id if form_data else '' }}" placeholder="Enter your Student ID" >
            
            {% if errors.student_id %}
                <div class="text-danger">{{ errors.student_id }}</div>
            {% endif %}
        </div>

        <!-- First Name -->
        <div class="mb-3">
            <label for="firstName" class="form-label">First Name</label>
            <input type="text" class="form-control" id="firstName" name="first_name" value="{{ form_data.first_name if form_data else '' }}" placeholder="Enter your First Name" >
            
            {% if errors.first_name %}
                <div class="text-danger">{{ errors.first_name }}</div>
            {% endif %}
        </div>

        <!-- Last Name -->
        <div class="mb-3">
            <label for="lastName" class="form-label">Last Name</label>
            <input type="text" class="form-control" id="lastName" name="last_name" value="{{ form_data.last_name if form_data else '' }}" placeholder="Enter your Last Name" >
        
            {% if errors.last_name %}
                <div class="text-danger">{{ errors.last_name }}</div>
            {% endif %}
        </div>

        <!-- Middle Name -->
        <div class="mb-3">
            <label for="middleName" class="form-label">Middle Name</label>
            <input type="text" class="form-control" id="middleName" name="middle_name" value="{{ form_data.middle_name if form_data else '' }}" placeholder="Enter your Middle Name">
        </div>

        <!-- Email -->
        <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input type="email" class="form-control" id="email" name="email" value="{{ form_data.email if form_data else '' }}" placeholder="Enter your Email" >
        
            {% if errors.email %}
                <div class="text-danger">{{ errors.email }}</div>
            {% endif %}
        </div>

        <!-- Telephone -->
        <div class="mb-3">
            <label for="telephone" class="form-label">Telephone</label>
            <input type="tel" class="form-control" id="telephone" name="telephone" value="{{ form_data.telephone if form_data else '' }}" placeholder="Enter your Telephone Number" >
        
            {% if errors.telephone %}
                <div class="text-danger">{{ errors.telephone }}</div>
            {% endif %}
        </div>

        <!-- Gender -->
        <div class="mb-3">
            <label for="gender" class="form-label">Gender</label>
            <select id="gender" name="gender" class="form-control" >
                <option value="" disabled {% if not form_data.gender %}selected{% endif %}>Select Gender</option>
                <option value="male" {% if form_data.gender == 'male' %}selected{% endif %}>Male</option>
                <option value="female" {% if form_data.gender == 'female' %}selected{% endif %}>Female</option>
                <option value="other" {% if form_data.gender == 'other' %}selected{% endif %}>Other</option>
            </select>

            {% if errors.gender %}
                <div class="text-danger">{{ errors.gender }}</div>
            {% endif %}
        </div>

        <!-- Level of Education -->
        <div class="mb-3">
            <label for="educationLevel" class="form-label">Level of Education</label>
            <select id="educationLevel" name="education_level" class="form-control" >
                <option value="" disabled {% if not form_data.educationLevel %}selected{% endif %}>Select Level of Education</option>
                <option value="undergraduate" {% if form_data.educationLevel == 'undergraduate' %}selected{% endif %}>Undergraduate</option>
                <option value="postgraduate" {% if form_data.educationLevel == 'postgraduate' %}selected{% endif %}>Postgraduate</option>
            </select>

            {% if errors.education_level %}
                <div class="text-danger">{{ errors.education_level }}</div>
            {% endif %}
        </div>

        <!-- Program Type -->
        <div class="mb-3">
            <label for="programType" class="form-label">Program Type</label>
            <select id="programType" name="programType" class="form-control" >
                <option value="" disabled {% if not form_data.programType %}selected{% endif %}>Select a Program</option>
                <option value="bachelors" {% if form_data.programType == 'bachelors' %}selected{% endif %}>Bachelors</option>
                <option value="masters" {% if form_data.programType == 'masters' %}selected{% endif %}>Masters</option>
                <option value="Mphil" {% if form_data.programType == 'Mphil' %}selected{% endif %}>Mphil</option>
                <option value="PhD" {% if form_data.programType == 'PhD' %}selected{% endif %}>PhD</option>
            </select>

            {% if errors.program_type %}
                <div class="text-danger">{{ errors.program_type }}</div>
            {% endif %}
        </div>

        <!-- Reason for Applying -->
        <div class="mb-3">
            <label for="reason" class="form-label">Reason for Applying for Accommodation</label>
            <textarea id="reason" name="reason_for_applying" class="form-control" rows="3"  placeholder="State your reason for applying for accommodation" >{{ form_data.reason_for_applying if form_data else '' }}</textarea>
        
            {% if errors.reason_for_applying %}
                <div class="text-danger">{{ errors.reason_for_applying }}</div>
            {% endif %}
        </div>

        <!-- Co-curricular Activities -->
        <div class="mb-3">
            <label for="activities" class="form-label">Co-curricular Activities</label>
            <textarea id="activities" name="co_curricular_activities" class="form-control" rows="3"  placeholder="List any co-curricular activities you are involved in">{{ form_data.co_curricular_activities if form_data else '' }}</textarea>
        </div>

        <!-- Agreement -->
        <div class="mb-4">
            <h5>Agreement</h5>
            <p>
                Please be advised that the information provided on your application to The University will be used by the Halls of Residence to process your application:
            </p>
            <ul>
                <li>Acceptance to the University does not guarantee an assignment to a room.</li>
                <li>Application to reside in Hall does not guarantee a room.</li>
                <li>The University's regulation on conduct and policies under which housing facilities are operated must be observed at all times during the period of residence.</li>
                <li>It is my responsibility to update my contact information.</li>
                <li>If I fail to respond to ANY correspondence from the Halls of Residence by the stated deadline my application will be canceled.</li>
                <li>Persons who have been offered and accepted a place in a hall will only be guaranteed accommodation for a period of one academic year, provided that all terms and conditions of the Hall Agreement are adhered to.</li>
            </ul>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="agreement" name="agreement" {% if form_data.agreement %}checked{% endif %} >
                <label class="form-check-label" for="agreement">I accept</label>
            </div>

            {% if errors.agreement %}
                <div class="text-danger">{{ errors.agreement }}</div>
            {% endif %}
        </div>

        {% if form_data.action == 'book'%}
            <!-- Submit Button -->
            <div class="text-center">
                <button type="submit" class="btn btn-success">Submit Application</button>
            </div>
        {% endif %}
        {% if form_data.action == 'edit'%}
            <!-- Submit Button -->
            <div class="text-center">
                <button type="submit" class="btn btn-warning">Edit Application</button>
            </div>
        {% endif %}
    </form>
</div>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link href="{{ url_for("static", filename="css/styles.css") }}" rel="stylesheet">

    {% block head %}{% endblock head %}
</head>
<body>
    {% block body %}{% endblock body %}
</body>

templates/login.html
{% extends "base.html" %}

{% block head %}
<title>Login | UWIDormFinder</title>
<link href="{{ url_for('static', filename='css/login.css') }}" rel="stylesheet">
{% endblock head %}

{% block body %}
<div class="login-card">
    <h2 class="text-center mb-4">Login to UWIDormFinder</h2>

    
    <form method="POST" action='/login' novalidate>
        <div class="mb-3">
            <label for="userID" class="form-label">Username</label>
            <input type="text" class="form-control" id="userID" name="userID" required>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password" required>
        </div>
        <button type="submit" class="btn btn-success w-100">Login</button>
    </form>
    
</div>
{% endblock body %}

templates/searchroom.html
{% extends "sidebar.html" %}

{% block content %}
    <!-- Main Content -->
    <div class="content p-4 mx-auto" style="width: 50%; max-width: 1200px;">
        <h1 class="text-center mb-4">Search for a Room</h1>
        <form method="POST" action="{{ url_for('searchroom.search_room') }}">
            <!-- Room Type -->
            <div class="mb-3">
                <label for="roomType" class="form-label">Room Type</label>
                <select id="roomType" name="room_type" class="form-control">
                    <option value="" disabled selected>Select Room Type</option>
                    <option value="Single">Single</option>
                    <option value="Double">Double</option>
                    <option value="Suite">Disable</option>
                </select>
            </div>

            <!-- Dormitory -->
            <div class="mb-3">
                <label for="dormitory" class="form-label">Dormitory Building</label>
                <select id="dormitory" name="dormitory" class="form-control">
                    <option value="" disabled selected>Select Dormitory</option>
                    <option value="1">Building 1</option>
                    <option value="2">Building 2</option>
                    <option value="3">Building 3</option>
                    <option value="4">Building 4</option>
                </select>
            </div>

            <!-- Level -->
            <div class="mb-3">
                <label for="level" class="form-label">Preferred Floor</label>
                <select id="level" name="level" class="form-control">
                    <option value="" disabled selected>Select Preferred Floor</option>
                    <option value="1">1st Floor</option>
                    <option value="2">2nd Floor</option>
                    <option value="3">3rd Floor</option>
                    <option value="4">4th Floor</option>
                    <option value="5">5th Floor</option>
                    <option value="6">6th Floor</option>
                </select>
            </div>

            <!-- Availability -->
            <div class="mb-3">
                <label for="availability" class="form-label">Availability</label>
                <select id="availability" name="availability" class="form-control">
                    <option value="" disabled selected>Select Availability</option>
                    <option value="now">Available Now</option>
                    <option value="upcoming">Upcoming Semester</option>
                </select>
            </div>

            <!-- Buttons -->
            <div class="d-flex justify-content-between">
                <button type="reset" class="btn btn-secondary">Reset</button>
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </form>

        <!-- Room Results -->
        {% if rooms %}
            <div class="container mt-5">
                <h3>Irvine Hall Rooms</h3>
                {% for room in rooms %}
                    <div class="card mb-3">
                        <div class="row g-0">
                            <!-- Image -->
                            <div class="col-md-4">
                                <img src="{{ url_for("static", filename=room.get_image_url()) }}" class="img-fluid rounded-start" alt="Room Image">
                            </div>
                            <!-- Text -->
                            <div class="col-md-8 d-flex align-items-center">
                                <div class="card-body">
                                    <h5 class="card-title">{{ room.get_room_type().title() ~ " Rooms for Building " ~ room.get_building() ~ " - Floor Level " ~ room.get_floor_number() }}</h5>
                                    <p class="card-text">{{ room.get_description() }}</p>
                                    <!-- <p class="card-text"><small class="text-muted">Available: {{ room.available_rooms }}</small></p> -->
                                    
                                    <div class="d-flex justify-content-between align-items-center">
                                        <small class="text-muted">Available: {{ room.get_available_rooms() }}</small>
                                        <a href="{{ url_for('bookroom.bookroom', room_id=room.get_room_id(), action='book') }}" class="btn btn-success">Book Room</a>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>

{% endblock content %}

templates/sidebar.html
{% extends "base.html" %}

{% block head %}
<title>Dashboard | UWIDormFinder</title>
<link href="{{ url_for('static', filename='css/dashboard.css') }}" rel="stylesheet">
{% endblock head %}

{% block body %}
<div class="d-flex">
    <!-- Sidebar -->
    <div class="sidebar 
        {% if user.getuserType() == 'Student' %}
            bg-success
        {% elif user.getuserType() == 'IT' %}
            bg-warning
        {% elif user.getuserType() == 'Admin' %}
            bg-orange
        {% endif %} "
    
    >
        <h4 class="text-center">UWIDormFinder</h4>
        <hr>
        <nav class="nav flex-column">
            <a class="nav-link" href="{{ url_for('dashboard.dashboard')}}">Dashboard</a>
            
            <!-- Conditional rendering based on usertype -->
            {% if user.getuserType() == 'Student' %}
                <a class="nav-link" href="{{ url_for('dashboard.room_search')}}">Room Search</a>
                <a class="nav-link" href="#">View Booking</a>
                <a class="nav-link" href="#">Track Application</a>
            {% elif user.getuserType() == 'Admin' %}
                <!--  <a class="nav-link" href="#">Track Application</a> -->
                <!--  <a class="nav-link" href="#">Update Application Status</a> -->
            {% elif user.getuserType() == 'IT' %}
                <a class="nav-link" href="{{ url_for('dashboard.admin_account_page', userID=user.getuserID()) }}">Create Admin Account</a>
                <a class="nav-link" href="#">System Log</a>
            {% endif %}
        </nav>
        <div class="profile">
            <div class="dropdown">
                <img src="https://via.placeholder.com/50" id="profileDropdown" data-bs-toggle="dropdown" aria-expanded="false" alt="User Profile">
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profileDropdown">
                    <li><a class="dropdown-item" href="#">Profile Settings</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{{ url_for('dashboard.logout')}}">Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
    
    {% block content %}
    
    
    {% endblock content %}
</div>
    
    <!-- Bootstrap 5 JS (Optional for Dropdowns) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    {% endblock body %}
    